{
  "openapi": "3.0.0",
  "info": {
    "title": "Aluguel de Carros",
    "description": "API para aluguel de carros",
    "termsOfService": "http://swagger.io/terms/",
    "contact": {
      "email": "giovani.alves121@gmail.com",
      "name": "Giovani Alves"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000/api/v1",
      "description": "Servidor de desenvolvimento"
    }
  ],
  "host": "localhost:3000",
  "basePath": "/api/v1",
  "tags": [
    {
      "name": "Autenticação",
      "description": "Operações de autenticação"
    },
    {
      "name": "Usuários",
      "description": "Operações com usuários"
    },
    {
      "name": "Carros",
      "description": "Operações com carros"
    },
    {
      "name": "Alugueis",
      "description": "Operações com alugueis"
    }
  ],
  "schemes": ["http"],
  "components": {
    "schemas": {
      "Car": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "year": {
            "type": "integer"
          },
          "model": {
            "type": "string"
          },
          "dailyRate": {
            "type": "integer"
          },
          "available": {
            "type": "boolean"
          }
        }
      },
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Register": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dateOfBirth": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dateOfBirth": {
            "type": "string"
          }
        }
      },
      "Rental": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            }
          },
          "car": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "model": {
                "type": "string"
              },
              "year": {
                "type": "integer"
              }
            }
          },
          "total": {
            "type": "integer"
          },
          "startDate": {
            "type": "string"
          },
          "endDate": {
            "type": "string"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/cars": {
      "get": {
        "tags": ["Carros"],
        "summary": "Retorna todos os carros",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de carros",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Car"
                  }
                },
                "example": [
                  {
                    "id": "cm2729dj300008yo8ksva2ytl",
                    "year": 2020,
                    "model": "Toyota Camry",
                    "dailyRate": 50,
                    "available": true
                  }
                ]
              }
            }
          },
          "400": {
            "description": "Nenhum carro encontrado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Failed to get cars"
                }
              }
            }
          }
        }
      }
    },
    "/cars/{id}": {
      "get": {
        "tags": ["Carros"],
        "summary": "Retorna um carro específico",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Retorna um carro",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Car"
                },
                "example": {
                  "id": "cm2729dj300008yo8ksva2ytl",
                  "year": 2020,
                  "model": "Toyota Camry",
                  "dailyRate": 50,
                  "available": true
                }
              }
            }
          },
          "400": {
            "description": "Nenhum carro encontrado",
            "content": {
              "application/json": {
                "oneOf": [
                  {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string"
                        }
                      }
                    },
                    "example": {
                      "message": "Car ID is required"
                    }
                  },
                  {
                    "schema": {
                      "type": "object",
                      "properties": {
                        "message": {
                          "type": "string"
                        }
                      }
                    },
                    "example": {
                      "message": "Failed to get car"
                    }
                  }
                ]
              }
            }
          },
          "404": {
            "description": "Car not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Car not found"
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": ["Autenticação"],
        "summary": "Realiza login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Login"
              },
              "example": {
                "email": "john.doe@acme.co",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Lista de carros",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNtMjcyYmF6aDAwMDB5NmIwdTBnMjcxYW4iLCJuYW1lIjoiR2lvdmFuaSBBbHZlcyIsImlhdCI6MTcyODc5MjM0NSwiZXhwIjoxNzI4ODc4NzQ1fQ.BqXSTTtbTH0lpvcOYbQG-0Sdm2qGx6gs3owyfraWrcU"
                }
              }
            }
          },
          "400": {
            "description": "Falha ao realizar login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Failed to login"
                }
              }
            }
          },
          "401": {
            "description": "Credenciais inválidas",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/register": {
      "post": {
        "tags": ["Autenticação"],
        "summary": "Realiza registro",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "$ref": "#/components/schemas/Register"
              },
              "example": {
                "email": "john.doe@acme.co",
                "password": "123456",
                "name": "John Doe",
                "dateOfBirth": "1990-01-01"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Lista de carros",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "email": "john.doe@acme.co",
                  "password": "123456",
                  "name": "John Doe",
                  "dateOfBirth": "1990-01-01"
                }
              }
            }
          },
          "400": {
            "description": "Falha ao realizar login",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Failed to login"
                }
              }
            }
          },
          "401": {
            "description": "Credenciais inválidas",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Invalid credentials"
                }
              }
            }
          }
        }
      }
    },
    "/users/me": {
      "get": {
        "tags": ["Usuários"],
        "summary": "Retona dados do usuário logado",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário logado",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/User"
                },
                "example": {
                  "id": "cm2729dj300008yo8ksva2ytl",
                  "email": "john.doe@acme.co",
                  "name": "John Doe",
                  "dateOfBirth": "1990-01-01"
                }
              }
            }
          },
          "400": {
            "description": "Failed to get user",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Failed to get user"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Unauthorized"
                }
              }
            }
          },
          "404": {
            "description": "User not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "User not found"
                }
              }
            }
          }
        }
      }
    },
    "/rentals": {
      "get": {
        "tags": ["Alugueis"],
        "summary": "Retorna todos os alugueis do usuário",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Lista de alugueis",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Rental"
                  }
                },
                "example": [
                  {
                    "id": "cm2729dj300008yo8ksva2ytl",
                    "user": {
                      "id": "cm2729dj300008yo8ksva2ytl",
                      "email": "john.doe@acme.co",
                      "name": "John Doe",
                      "dateOfBirth": "1990-01-01"
                    },
                    "car": {
                      "id": "cm2729dj300008yo8ksva2ytl",
                      "model": "Toyota Camry",
                      "year": 2020
                    },
                    "total": 100,
                    "startDate": "2021-08-01",
                    "endDate": "2021-08-03"
                  }
                ]
              }
            }
          },
          "400": {
            "description": "User ID is required",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "User ID is required"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Alugueis"],
        "summary": "Realiza um aluguel",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userId": {
                    "type": "string"
                  },
                  "carId": {
                    "type": "string"
                  },
                  "startDate": {
                    "type": "string"
                  },
                  "endDate": {
                    "type": "string"
                  }
                },
                "example": {
                  "userId": "cm2729dj300008yo8ksva2ytl",
                  "carId": "cm2729dj300008yo8ksva2ytl",
                  "total": 100,
                  "startDate": "2021-08-01",
                  "endDate": "2021-08-03"
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "Aluguel realizado com sucesso",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "$ref": "#/components/schemas/Rental"
                  },
                  "example": {
                    "id": "cm2729dj300008yo8ksva2ytl",
                    "user": {
                      "id": "cm2729dj300008yo8ksva2ytl",
                      "email": "john.doe@acme.co",
                      "name": "John Doe",
                      "dateOfBirth": "1990-01-01"
                    },
                    "car": {
                      "id": "cm2729dj300008yo8ksva2ytl",
                      "model": "Toyota Camry",
                      "year": 2020
                    },
                    "total": 100,
                    "startDate": "2021-08-01",
                    "endDate": "2021-08-03"
                  }
                }
              }
            },
            "400": {
              "content": {
                "application/json": {
                  "oneOf": [
                    {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "type": "string"
                          }
                        }
                      },
                      "example": {
                        "message": "Missing required fields"
                      }
                    },
                    {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "type": "string"
                          }
                        }
                      },
                      "example": {
                        "message": "Failed to create rental"
                      }
                    }
                  ]
                }
              }
            },
            "404": {
              "content": {
                "application/json": {
                  "oneOf": [
                    {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "type": "string"
                          }
                        }
                      },
                      "example": {
                        "message": "User not found"
                      }
                    },
                    {
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "type": "string"
                          }
                        }
                      },
                      "example": {
                        "message": "Car not found"
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/rentals/{id}": {
      "delete": {
        "tags": ["Alugueis"],
        "summary": "Deleta um aluguel",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Aluguel deletado com sucesso"
          },
          "400": {
            "description": "Rental ID is required",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Rental ID is required"
                }
              }
            }
          },
          "404": {
            "description": "Rental not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Rental not found"
                }
              }
            }
          }
        }
      },
      "get": {
        "tags": ["Alugueis"],
        "summary": "Retorna um aluguel específico",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Retorna um aluguel",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Rental"
                },
                "example": {
                  "id": "cm2729dj300008yo8ksva2ytl",
                  "user": {
                    "id": "cm2729dj300008yo8ksva2ytl",
                    "email": "john.doe@acme.co",
                    "name": "John Doe",
                    "dateOfBirth": "1990-01-01"
                  },
                  "car": {
                    "id": "cm2729dj300008yo8ksva2ytl",
                    "model": "Toyota Camry",
                    "year": 2020
                  },
                  "total": 100,
                  "startDate": "2021-08-01",
                  "endDate": "2021-08-03"
                }
              }
            }
          },
          "400": {
            "description": "Rental ID is required",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "message": "Rental ID is required"
                }
              }
            },
            "404": {
              "description": "Rental not found",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "properties": {
                      "message": {
                        "type": "string"
                      }
                    }
                  },
                  "example": {
                    "message": "Rental not found"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
